In [1]:
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
from scipy import sparse
import sys
from time import time
from IPython.core.debugger import set_trace

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder

In [2]:
from NNS import Recommender

In [3]:
clf = Recommender("user_based_NN", verbose=True)

In [4]:
clf.load_encoders(path_songs="data/label_encoder_songs_classes_.npy", path_users="data/label_encoder_users_classes_.npy")

In [5]:
X = sparse.load_npz("data/song-user_matrix_with_rating.npz")

In [6]:
clf.load_model(model_name="Item-User_KNN_model")

In [7]:
_10_random_songs = np.random.choice(clf.song_label_encoder.classes_,10)
print(_10_random_songs)
song_list = clf.song_label_encoder.transform(np.array(_10_random_songs)).squeeze()
song_list

['SOVQZBK12A6D4F8413' 'SODEPGO12A6D4F8882' 'SONWIGS12AB0189A23'
 'SOOTLSK12A8C13F68C' 'SOORQWE12AB017BA0F' 'SODYBPW12AAF3B3061'
 'SOAAMTH12AF729D4E5' 'SOBUFOW12A8AE48661' 'SOEFOIW12A8C138C0A'
 'SOGMAXP12A58A7CC35']


array([136045,  20971,  89505,  94961,  94556,  25973,    134,  11749,
        27843,  42691])

In [8]:
clf.recommend(song_list= _10_random_songs, full_name=True, return_song_id=True)


  recommended_songs_id  cosine distance
0   SOBIQRS12AB0185E55         0.939268
1   SOMQGGA12A8C13CCFF         0.858115
2   SONMIKJ12AF72A037D         0.937439
3   SOXWHDL12AB018E675         0.896243
4   SOAKRQZ12A5C5D4218         0.928117
5   SOOUCHE12AB018B8FA         0.920360
6   SOSDLQS12A6D4F9D84         0.940110
7   SOOISQZ12A8C139B0C         0.927044
8   SOQINBP12A6310E222         0.794572
9   SORIQMF12A6310E9DA         0.844919


(array(['SOBIQRS12AB0185E55', 'SOMQGGA12A8C13CCFF', 'SONMIKJ12AF72A037D',
        'SOXWHDL12AB018E675', 'SOAKRQZ12A5C5D4218', 'SOOUCHE12AB018B8FA',
        'SOSDLQS12A6D4F9D84', 'SOOISQZ12A8C139B0C', 'SOQINBP12A6310E222',
        'SORIQMF12A6310E9DA'], dtype=object),
 array([0.93926833, 0.85811479, 0.93743888, 0.89624283, 0.92811695,
        0.92036022, 0.9401101 , 0.92704422, 0.79457239, 0.8449193 ]))

In [9]:
clf.recommend(song_list=_10_random_songs, full_name=True, return_song_id=False)

   recommended_songs_code  cosine distance
0                    8762         0.939268
1                   81799         0.858115
2                   87071         0.937439
3                  148871         0.896243
4                    2742         0.928117
5                   95127         0.920360
6                  115153         0.940110
7                   92475         0.927044
8                  104541         0.794572
9                  110421         0.844919


(array([  8762,  81799,  87071, 148871,   2742,  95127, 115153,  92475,
        104541, 110421], dtype=int64),
 array([0.93926833, 0.85811479, 0.93743888, 0.89624283, 0.92811695,
        0.92036022, 0.9401101 , 0.92704422, 0.79457239, 0.8449193 ]))

In [10]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=True)

  recommended_songs_id  cosine distance
0   SOBIQRS12AB0185E55         0.939268
1   SOMQGGA12A8C13CCFF         0.858115
2   SONMIKJ12AF72A037D         0.937439
3   SOXWHDL12AB018E675         0.896243
4   SOAKRQZ12A5C5D4218         0.928117
5   SOOUCHE12AB018B8FA         0.920360
6   SOSDLQS12A6D4F9D84         0.940110
7   SOOISQZ12A8C139B0C         0.927044
8   SOQINBP12A6310E222         0.794572
9   SORIQMF12A6310E9DA         0.844919


(array(['SOBIQRS12AB0185E55', 'SOMQGGA12A8C13CCFF', 'SONMIKJ12AF72A037D',
        'SOXWHDL12AB018E675', 'SOAKRQZ12A5C5D4218', 'SOOUCHE12AB018B8FA',
        'SOSDLQS12A6D4F9D84', 'SOOISQZ12A8C139B0C', 'SOQINBP12A6310E222',
        'SORIQMF12A6310E9DA'], dtype=object),
 array([0.93926833, 0.85811479, 0.93743888, 0.89624283, 0.92811695,
        0.92036022, 0.9401101 , 0.92704422, 0.79457239, 0.8449193 ]))

In [11]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=False)

   recommended_songs_code  cosine distance
0                    8762         0.939268
1                   81799         0.858115
2                   87071         0.937439
3                  148871         0.896243
4                    2742         0.928117
5                   95127         0.920360
6                  115153         0.940110
7                   92475         0.927044
8                  104541         0.794572
9                  110421         0.844919


(array([  8762,  81799,  87071, 148871,   2742,  95127, 115153,  92475,
        104541, 110421], dtype=int64),
 array([0.93926833, 0.85811479, 0.93743888, 0.89624283, 0.92811695,
        0.92036022, 0.9401101 , 0.92704422, 0.79457239, 0.8449193 ]))

# same input


In [12]:
_1_song = np.random.choice(clf.song_label_encoder.classes_,1)
_1_same_song = np.array([_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song]).ravel()
_1_same_song

array(['SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5',
       'SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5',
       'SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5', 'SOVINEN12A8C1300A5',
       'SOVINEN12A8C1300A5'], dtype=object)

In [13]:
clf.recommend(song_list=_1_same_song, full_name=True, return_song_id=True)

  recommended_songs_id  cosine distance
0   SONDQFO12A8C140165         0.876292
1   SOINZUO12AB017FCC7         0.870728
2   SOGKBID12B0B808F05         0.865258
3   SOWDNPE12A8C144DCD         0.859029
4   SOYCTOH12A8C139F16         0.857085
5   SODNPLM12A8C13C612         0.855912
6   SOIJNHJ12A8C13BF06         0.846607
7   SOVLWXJ12A6D4F7302         0.835229
8   SOPURSM12A8C13B5BE         0.827146
9   SOFSJCX12A8C13009D         0.792587


(array(['SONDQFO12A8C140165', 'SOINZUO12AB017FCC7', 'SOGKBID12B0B808F05',
        'SOWDNPE12A8C144DCD', 'SOYCTOH12A8C139F16', 'SODNPLM12A8C13C612',
        'SOIJNHJ12A8C13BF06', 'SOVLWXJ12A6D4F7302', 'SOPURSM12A8C13B5BE',
        'SOFSJCX12A8C13009D'], dtype=object),
 array([0.87629195, 0.87072808, 0.86525799, 0.85902903, 0.85708451,
        0.85591237, 0.846607  , 0.83522949, 0.82714567, 0.7925869 ]))