In [1]:
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
from scipy import sparse
import sys
from time import time
from IPython.core.debugger import set_trace

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder

In [2]:
from NNS import Recommender, user_based_model

# Correct way to load and use model.
- There is simplier way to load it in next section (below this one)

In [3]:
clf = Recommender("user_based_NN", verbose=True)

In [4]:
clf.load_encoders(path_songs="data/label_encoder_songs_classes_.npy", path_users="data/label_encoder_users_classes_.npy")

In [5]:
X = sparse.load_npz("data/song-user_matrix_with_rating.npz")

In [6]:
clf.fit(X=X)
clf.save_model(model_name="Item-User_KNN_model")

In [7]:
_10_random_songs = np.random.choice(clf.song_label_encoder.classes_,10)
print(_10_random_songs)
song_list = clf.song_label_encoder.transform(np.array(_10_random_songs)).squeeze()
song_list

['SOWMXCV12A58A7A0BA' 'SOMECRM12A8C1440F3' 'SORKIXS12AF72A868A'
 'SOKNEVA12A8C13ACAF' 'SOGHWBG12A6D4F9BBA' 'SORSSPR12A8C131E7B'
 'SOTMSHF12AB0184E53' 'SOEYZPS12A8C134B76' 'SORBBMC12A81C2132C'
 'SOZUWUI12AB017F0FA']


array([141036,  78974, 110808,  68587,  41606, 112727, 123305,  32873,
       108744, 160044])

In [8]:
clf.recommend(song_list= _10_random_songs, full_name=True, return_song_id=True)


  recommended_songs_id  cosine distance
0   SOJLGOJ12AB0184ECC         0.899728
1   SOXIMAE12AB0185F48         0.907364
2   SOUCWNP12AF72A21ED         0.700951
3   SOCZBCY12AB0185EE1         0.859280
4   SOIGPLE12A6D4F9BC1         0.872743
5   SOGSFMU12A6D4F69AA         0.824318
6   SOFGSWJ12AB018AD28         0.826084
7   SOMHTFK12A6D4FA0C0         0.744828
8   SOEPJRT12A8C139672         0.843167
9   SOXZRHY12A8AE492FF         0.935288


(array(['SOJLGOJ12AB0184ECC', 'SOXIMAE12AB0185F48', 'SOUCWNP12AF72A21ED',
        'SOCZBCY12AB0185EE1', 'SOIGPLE12A6D4F9BC1', 'SOGSFMU12A6D4F69AA',
        'SOFGSWJ12AB018AD28', 'SOMHTFK12A6D4FA0C0', 'SOEPJRT12A8C139672',
        'SOXZRHY12A8AE492FF'], dtype=object),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [15]:
clf.recommend(song_list=_10_random_songs, full_name=True, return_song_id=False)

   recommended_songs_code  cosine distance
0                   61639         0.899728
1                  145771         0.907364
2                  127000         0.700951
3                   19552         0.859280
4                   54217         0.872743
5                   44216         0.824318
6                   34780         0.826084
7                   79826         0.744828
8                   30395         0.843167
9                  149639         0.935288


(array([ 61639, 145771, 127000,  19552,  54217,  44216,  34780,  79826,
         30395, 149639]),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [16]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=True)

  recommended_songs_id  cosine distance
0   SOJLGOJ12AB0184ECC         0.899728
1   SOXIMAE12AB0185F48         0.907364
2   SOUCWNP12AF72A21ED         0.700951
3   SOCZBCY12AB0185EE1         0.859280
4   SOIGPLE12A6D4F9BC1         0.872743
5   SOGSFMU12A6D4F69AA         0.824318
6   SOFGSWJ12AB018AD28         0.826084
7   SOMHTFK12A6D4FA0C0         0.744828
8   SOEPJRT12A8C139672         0.843167
9   SOXZRHY12A8AE492FF         0.935288


(array(['SOJLGOJ12AB0184ECC', 'SOXIMAE12AB0185F48', 'SOUCWNP12AF72A21ED',
        'SOCZBCY12AB0185EE1', 'SOIGPLE12A6D4F9BC1', 'SOGSFMU12A6D4F69AA',
        'SOFGSWJ12AB018AD28', 'SOMHTFK12A6D4FA0C0', 'SOEPJRT12A8C139672',
        'SOXZRHY12A8AE492FF'], dtype=object),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [17]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=False)

   recommended_songs_code  cosine distance
0                   61639         0.899728
1                  145771         0.907364
2                  127000         0.700951
3                   19552         0.859280
4                   54217         0.872743
5                   44216         0.824318
6                   34780         0.826084
7                   79826         0.744828
8                   30395         0.843167
9                  149639         0.935288


(array([ 61639, 145771, 127000,  19552,  54217,  44216,  34780,  79826,
         30395, 149639]),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

## same input


In [18]:
_1_song = np.random.choice(clf.song_label_encoder.classes_,1)
_1_same_song = np.array([_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song]).ravel()
_1_same_song

array(['SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276',
       'SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276',
       'SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276', 'SOSUVOQ12A8C138276',
       'SOSUVOQ12A8C138276'], dtype=object)

In [19]:
clf.recommend(song_list=_1_same_song, full_name=True, return_song_id=True)

  recommended_songs_id  cosine distance
0   SORXWAQ12A8C13827F         0.809840
1   SOMVGSE12A8C138279         0.803795
2   SOBPDVC12A3F1ED417         0.800757
3   SOVMIYF12AF72A0020         0.800333
4   SOEMPLB12A8C139F59         0.795741
5   SOWKKZQ12A8C13BD46         0.794399
6   SOIBMCL12A8C139F53         0.790343
7   SOYLPSW12A8C139F4D         0.785927
8   SOMCRES12A8C1383DC         0.776113
9   SOTXRPJ12A8C13844A         0.774591


(array(['SORXWAQ12A8C13827F', 'SOMVGSE12A8C138279', 'SOBPDVC12A3F1ED417',
        'SOVMIYF12AF72A0020', 'SOEMPLB12A8C139F59', 'SOWKKZQ12A8C13BD46',
        'SOIBMCL12A8C139F53', 'SOYLPSW12A8C139F4D', 'SOMCRES12A8C1383DC',
        'SOTXRPJ12A8C13844A'], dtype=object),
 array([0.80984029, 0.80379541, 0.80075693, 0.8003325 , 0.79574072,
        0.79439926, 0.79034303, 0.78592655, 0.77611317, 0.77459084]))

# Simplifed function for loading and setting model

In [20]:
model = user_based_model()

In [21]:
model.recommend(song_list= _10_random_songs, full_name=True, return_song_id=True)


  recommended_songs_id  cosine distance
0   SOJLGOJ12AB0184ECC         0.899728
1   SOXIMAE12AB0185F48         0.907364
2   SOUCWNP12AF72A21ED         0.700951
3   SOCZBCY12AB0185EE1         0.859280
4   SOIGPLE12A6D4F9BC1         0.872743
5   SOGSFMU12A6D4F69AA         0.824318
6   SOFGSWJ12AB018AD28         0.826084
7   SOMHTFK12A6D4FA0C0         0.744828
8   SOEPJRT12A8C139672         0.843167
9   SOXZRHY12A8AE492FF         0.935288


(array(['SOJLGOJ12AB0184ECC', 'SOXIMAE12AB0185F48', 'SOUCWNP12AF72A21ED',
        'SOCZBCY12AB0185EE1', 'SOIGPLE12A6D4F9BC1', 'SOGSFMU12A6D4F69AA',
        'SOFGSWJ12AB018AD28', 'SOMHTFK12A6D4FA0C0', 'SOEPJRT12A8C139672',
        'SOXZRHY12A8AE492FF'], dtype=object),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [22]:
model.recommend(song_list=_10_random_songs, full_name=True, return_song_id=False)

   recommended_songs_code  cosine distance
0                   61639         0.899728
1                  145771         0.907364
2                  127000         0.700951
3                   19552         0.859280
4                   54217         0.872743
5                   44216         0.824318
6                   34780         0.826084
7                   79826         0.744828
8                   30395         0.843167
9                  149639         0.935288


(array([ 61639, 145771, 127000,  19552,  54217,  44216,  34780,  79826,
         30395, 149639]),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [23]:
model.recommend(song_list= song_list, full_name=False, return_song_id=True)

  recommended_songs_id  cosine distance
0   SOJLGOJ12AB0184ECC         0.899728
1   SOXIMAE12AB0185F48         0.907364
2   SOUCWNP12AF72A21ED         0.700951
3   SOCZBCY12AB0185EE1         0.859280
4   SOIGPLE12A6D4F9BC1         0.872743
5   SOGSFMU12A6D4F69AA         0.824318
6   SOFGSWJ12AB018AD28         0.826084
7   SOMHTFK12A6D4FA0C0         0.744828
8   SOEPJRT12A8C139672         0.843167
9   SOXZRHY12A8AE492FF         0.935288


(array(['SOJLGOJ12AB0184ECC', 'SOXIMAE12AB0185F48', 'SOUCWNP12AF72A21ED',
        'SOCZBCY12AB0185EE1', 'SOIGPLE12A6D4F9BC1', 'SOGSFMU12A6D4F69AA',
        'SOFGSWJ12AB018AD28', 'SOMHTFK12A6D4FA0C0', 'SOEPJRT12A8C139672',
        'SOXZRHY12A8AE492FF'], dtype=object),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

In [24]:
model.recommend(song_list= song_list, full_name=False, return_song_id=False)

   recommended_songs_code  cosine distance
0                   61639         0.899728
1                  145771         0.907364
2                  127000         0.700951
3                   19552         0.859280
4                   54217         0.872743
5                   44216         0.824318
6                   34780         0.826084
7                   79826         0.744828
8                   30395         0.843167
9                  149639         0.935288


(array([ 61639, 145771, 127000,  19552,  54217,  44216,  34780,  79826,
         30395, 149639]),
 array([0.89972778, 0.90736421, 0.70095122, 0.85928049, 0.87274305,
        0.82431791, 0.8260836 , 0.74482783, 0.84316692, 0.9352883 ]))

## same input


In [25]:
model.recommend(song_list=_1_same_song, full_name=True, return_song_id=True)

  recommended_songs_id  cosine distance
0   SORXWAQ12A8C13827F         0.809840
1   SOMVGSE12A8C138279         0.803795
2   SOBPDVC12A3F1ED417         0.800757
3   SOVMIYF12AF72A0020         0.800333
4   SOEMPLB12A8C139F59         0.795741
5   SOWKKZQ12A8C13BD46         0.794399
6   SOIBMCL12A8C139F53         0.790343
7   SOYLPSW12A8C139F4D         0.785927
8   SOMCRES12A8C1383DC         0.776113
9   SOTXRPJ12A8C13844A         0.774591


(array(['SORXWAQ12A8C13827F', 'SOMVGSE12A8C138279', 'SOBPDVC12A3F1ED417',
        'SOVMIYF12AF72A0020', 'SOEMPLB12A8C139F59', 'SOWKKZQ12A8C13BD46',
        'SOIBMCL12A8C139F53', 'SOYLPSW12A8C139F4D', 'SOMCRES12A8C1383DC',
        'SOTXRPJ12A8C13844A'], dtype=object),
 array([0.80984029, 0.80379541, 0.80075693, 0.8003325 , 0.79574072,
        0.79439926, 0.79034303, 0.78592655, 0.77611317, 0.77459084]))