In [1]:
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
from scipy import sparse
import sys
from time import time
from IPython.core.debugger import set_trace

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder

In [2]:
from NNS import Recommender, user_based_model

# Correct way to load and use model.
- There is simplier way to load it in next section (below this one)

In [3]:
clf = Recommender("user_based_NN", verbose=True)

In [4]:
clf.load_encoders(path_songs="data/label_encoder_songs_classes_.npy", path_users="data/label_encoder_users_classes_.npy")

In [5]:
X = sparse.load_npz("data/song-user_matrix_with_rating.npz")

In [6]:
clf.fit(X=X)
clf.save_model(model_name="Item-User_KNN_model")

In [7]:
_10_random_songs = np.random.choice(clf.song_label_encoder.classes_,10)
print(_10_random_songs)
song_list = clf.song_label_encoder.transform(np.array(_10_random_songs)).squeeze()
song_list

['SOUHPCH12A8C1397DE' 'SOATVOC12A8AE45DC6' 'SOWNQOF12AB017B996'
 'SOGPFFH12A8AE46A3C' 'SOPCZSP12AC3DF57B8' 'SOHMACD12A6D4F9582'
 'SONHTYA12AB0186812' 'SODVQKS12AB017BB6B' 'SOCHVTF12AB017D77C'
 'SOTLJLP12A58A7E694']


array([128077,   5025, 141198,  43494,  97208,  49140,  85964,  25319,
        15246, 122973])

In [8]:
clf.recommend(song_list= _10_random_songs, full_name=True, return_song_id=True)


  recommended_songs_id  cosine distance
0   SONMPJJ12AB0183AF8         0.773093
1   SOOWBLY12A8C1328D8         0.833333
2   SOGTCEZ12A6D4F8B9D         0.878302
3   SOPMPIG12AB018076F         0.928088
4   SOCPZST12A8C1358C8         0.919418
5   SOANPZB12A58A77F80         0.838763
6   SODYSZA12A6D4FA267         0.939807
7   SOXRZGX12AB01857E0         0.909425
8   SOMRGAI12A8C1426CA         0.791667
9   SOPZJDL12A6D4F93A6         0.921066


(array(['SONMPJJ12AB0183AF8', 'SOOWBLY12A8C1328D8', 'SOGTCEZ12A6D4F8B9D',
        'SOPMPIG12AB018076F', 'SOCPZST12A8C1358C8', 'SOANPZB12A58A77F80',
        'SODYSZA12A6D4FA267', 'SOXRZGX12AB01857E0', 'SOMRGAI12A8C1426CA',
        'SOPZJDL12A6D4F93A6'], dtype=object),
 array([0.77309334, 0.83333333, 0.8783022 , 0.92808825, 0.9194177 ,
        0.83876305, 0.93980707, 0.90942471, 0.79166667, 0.9210663 ]))

In [9]:
clf.recommend(song_list=_10_random_songs, full_name=True, return_song_id=False)

   recommended_songs_code  cosine distance
0                   87145         0.773093
1                   95574         0.833333
2                   44445         0.878302
3                   99470         0.928088
4                   17263         0.919418
5                    3495         0.838763
6                   26126         0.939807
7                  147907         0.909425
8                   82035         0.791667
9                  102395         0.921066


(array([ 87145,  95574,  44445,  99470,  17263,   3495,  26126, 147907,
         82035, 102395], dtype=int64),
 array([0.77309334, 0.83333333, 0.8783022 , 0.92808825, 0.9194177 ,
        0.83876305, 0.93980707, 0.90942471, 0.79166667, 0.9210663 ]))

In [10]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=True)

  recommended_songs_id  cosine distance
0   SONMPJJ12AB0183AF8         0.773093
1   SOOWBLY12A8C1328D8         0.833333
2   SOGTCEZ12A6D4F8B9D         0.878302
3   SOPMPIG12AB018076F         0.928088
4   SOCPZST12A8C1358C8         0.919418
5   SOANPZB12A58A77F80         0.838763
6   SODYSZA12A6D4FA267         0.939807
7   SOXRZGX12AB01857E0         0.909425
8   SOMRGAI12A8C1426CA         0.791667
9   SOPZJDL12A6D4F93A6         0.921066


(array(['SONMPJJ12AB0183AF8', 'SOOWBLY12A8C1328D8', 'SOGTCEZ12A6D4F8B9D',
        'SOPMPIG12AB018076F', 'SOCPZST12A8C1358C8', 'SOANPZB12A58A77F80',
        'SODYSZA12A6D4FA267', 'SOXRZGX12AB01857E0', 'SOMRGAI12A8C1426CA',
        'SOPZJDL12A6D4F93A6'], dtype=object),
 array([0.77309334, 0.83333333, 0.8783022 , 0.92808825, 0.9194177 ,
        0.83876305, 0.93980707, 0.90942471, 0.79166667, 0.9210663 ]))

In [11]:
clf.recommend(song_list= song_list, full_name=False, return_song_id=False)

   recommended_songs_code  cosine distance
0                   87145         0.773093
1                   95574         0.833333
2                   44445         0.878302
3                   99470         0.928088
4                   17263         0.919418
5                    3495         0.838763
6                   26126         0.939807
7                  147907         0.909425
8                   82035         0.791667
9                  102395         0.921066


(array([ 87145,  95574,  44445,  99470,  17263,   3495,  26126, 147907,
         82035, 102395], dtype=int64),
 array([0.77309334, 0.83333333, 0.8783022 , 0.92808825, 0.9194177 ,
        0.83876305, 0.93980707, 0.90942471, 0.79166667, 0.9210663 ]))

## same input


In [12]:
_1_song = np.random.choice(clf.song_label_encoder.classes_,1)
_1_same_song = np.array([_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song,_1_song]).ravel()
_1_same_song

array(['SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E',
       'SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E',
       'SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E', 'SOCVUMR12A8C13803E',
       'SOCVUMR12A8C13803E'], dtype=object)

In [13]:
clf.recommend(song_list=_1_same_song, full_name=True, return_song_id=True)

  recommended_songs_id  cosine distance
0   SOCVLSM12A6D4F79CB         0.881873
1   SOERRLC12A6D4F731B         0.869552
2   SOAHGIJ12AB01880F7         0.868242
3   SONPHYK12A58A7BA09         0.860384
4   SOOHTKR12AB0186A6D         0.859813
5   SOGDWVU12A6D4FB0C6         0.844759
6   SOZTDEY12AB018CC29         0.839635
7   SOREZLS12A8C136347         0.819225
8   SOOWZDS12AB0186D6F         0.813405
9   SOXUMTB12AB0186A80         0.812768


(array(['SOCVLSM12A6D4F79CB', 'SOERRLC12A6D4F731B', 'SOAHGIJ12AB01880F7',
        'SONPHYK12A58A7BA09', 'SOOHTKR12AB0186A6D', 'SOGDWVU12A6D4FB0C6',
        'SOZTDEY12AB018CC29', 'SOREZLS12A8C136347', 'SOOWZDS12AB0186D6F',
        'SOXUMTB12AB0186A80'], dtype=object),
 array([0.88187252, 0.86955152, 0.86824221, 0.86038445, 0.85981296,
        0.84475883, 0.83963459, 0.81922462, 0.8134049 , 0.81276848]))

# Simplifed function for loading and setting model

In [14]:
model = user_based_model()

In [ ]:
model.recommend(song_list= _10_random_songs, full_name=True, return_song_id=True)


In [ ]:
model.recommend(song_list=_10_random_songs, full_name=True, return_song_id=False)

In [ ]:
model.recommend(song_list= song_list, full_name=False, return_song_id=True)

In [ ]:
model.recommend(song_list= song_list, full_name=False, return_song_id=False)

## same input


In [ ]:
model.recommend(song_list=_1_same_song, full_name=True, return_song_id=True)